# -*- coding: utf-8 -*-
"""
Created on Mon Jul 26 18:35:28 2021

@author: Dr. Birko-Katarina Ruzicka
"""
import json


with open('StarTrekDialogue.json', 'r') as read_file:
    all_series = json.load(read_file)
del(read_file)
    

tos = all_series['TOS']
tos['tos_000']['BOYCE'].extend(tos['tos_000'].pop('BOYCE [OC}'))
del tos['tos_000']['PIKE: Vina?\r ORION']
tos['tos_000']['PIKE'].extend(tos['tos_000'].pop('PIKE;'))
tos['tos_000']['VINA'].extend(tos['tos_000'].pop('VINA;'))
tos['tos_012']['KEEPER'].extend(tos['tos_012'].pop('KEEPER;'))
tos['tos_012']['PIKE'].extend(tos['tos_012'].pop('PIKE;'))
tos['tos_012']['VINA'].extend(tos['tos_012'].pop('VINA;'))
tos['tos_013']['KIRK'].extend(tos['tos_013'].pop('KIRK;'))
tos['tos_014']['KIRK'].extend(tos['tos_014'].pop('KIRK: When they opened fire. Perhaps necessary when they use their\r weapon. SPOCK'))
tos['tos_015']['KIRK'].extend(tos['tos_015'].pop('KIRK;'))
tos['tos_015']['RODRIGUEZ'].extend(tos['tos_015'].pop('RODRIQUEZ'))
tos['tos_017']['KIRK'].extend(tos['tos_017'].pop('KIRK;'))
tos['tos_018']['KIRK'].extend(tos['tos_018'].pop('KIRK;'))
tos['tos_018']['SPOCK'].extend(tos['tos_018'].pop('SPOCK;'))
tos['tos_020']['KIRK'].extend(tos['tos_020'].pop('KIRK;'))
tos['tos_021']['KIRK'].extend(tos['tos_021'].pop('KIRK;'))
tos['tos_024']['ELIAS'].extend(tos['tos_024'].pop('ELIAS;'))
tos['tos_026']['KIRK'].extend(tos['tos_026'].pop('KIRK;'))
tos['tos_027']['KIRK'].extend(tos['tos_027'].pop('KIRK;'))
tos['tos_027']['SPOCK'].extend(tos['tos_027'].pop('SPOCK;'))
tos['tos_029']['KIRK'].extend(tos['tos_029'].pop('KIRK;'))
tos['tos_030']['MCCOY'].extend(tos['tos_030'].pop('MCCOY;'))
tos['tos_031']['KIRK'].extend(tos['tos_031'].pop('KIRK;'))
tos['tos_032']['UHURA'].extend(tos['tos_032'].pop("UHURA: Mister Scott's engineers are working on them now. UHURA"))
tos['tos_032']['SPOCK'].extend(tos['tos_032'].pop('SPOCK;'))
tos['tos_033']['THARN'].extend(tos['tos_033'].pop('THARN [on viewscreen'))
tos['tos_034']['SPOCK'].extend(tos['tos_034'].pop('SPOCK: Readings are getting weaker, Captain. Wide\r variation in energy transmissions, as though Vaal were trying to draw\r on other sources.\r KIRK'))
tos['tos_034']['KIRK'].extend(tos['tos_034'].pop('KIRK;'))
tos['tos_035']['SPOCK'].extend(tos['tos_035'].pop('SPOCK;'))
tos['tos_036']['KIRK'].extend(tos['tos_036'].pop('KIRK;'))
tos['tos_037']['ALICES'].extend(tos['tos_037'].pop('NORMAN and ALICES'))
tos['tos_037']['ALICES'].extend(tos['tos_037'].pop('ALICE 118+2'))
tos['tos_037']['ALICES'].extend(tos['tos_037'].pop('ALICE and KIRK'))
tos['tos_037']['SCOTT'].extend(tos['tos_037'].pop('SCOTT;'))
tos['tos_039']['KIRK'].extend(tos['tos_039'].pop('KIRK;'))
tos['tos_044']['SPOCK'].extend(tos['tos_044'].pop('SPOCK;'))
del tos['tos_044']['{K7']
tos['tos_045']['SHAHNA'].extend(tos['tos_045'].pop('SHAHNA:'))
tos['tos_046']['KIRK'].extend(tos['tos_046'].pop('KIRK;'))
tos['tos_048']['MCCOY'].extend(tos['tos_048'].pop("MCCOY: This pig iron is almost carbon-free. That village\r furnace certainly didn't produce it. People's exhibit number two.\r Cold-rolled gun barrel rod fashioned to look homemade. You were right\r about the Klingons, Jim.\r KIRK"))
tos['tos_049']['KIRK'].extend(tos['tos_049'].pop('KIRK;'))
tos['tos_049']['SPOCK'].extend(tos['tos_049'].pop('SPOCK: These others, they were stored differently than you, but it was\r your task to remain in the receptacle out there KIRK'))
tos['tos_050']['KIRK'].extend(tos['tos_050'].pop('KIRK;'))
tos['tos_050']['SPOCK'].extend(tos['tos_050'].pop('SPOCK;'))
tos['tos_052']['KIRK'].extend(tos['tos_052'].pop('KIRK;'))
tos['tos_056']['KARA'].extend(tos['tos_056'].pop('KARA;'))
tos['tos_057']['SPOCK'].extend(tos['tos_057'].pop('SPOCK;'))
tos['tos_057']['SCOTT'].extend(tos['tos_057'].pop('SCOTT;'))
tos['tos_058']['KIRK'].extend(tos['tos_058'].pop('KIRK;'))
tos['tos_058']['MIRAMANEE'].extend(tos['tos_058'].pop('MIRAMANEE@'))
tos['tos_059']['KIRK'].extend(tos['tos_059'].pop('KIRK: And their present behaviour explained by a fear of punishment.\r SPOCK'))
tos['tos_060']['KIRK'].extend(tos['tos_060'].pop('KIRK;'))
tos['tos_060']['MARVICK'].extend(tos['tos_060'].pop('MARVICK;'))
tos['tos_066']['MCCOY'].extend(tos['tos_066'].pop('MCCOY;'))
tos['tos_071']['KIRK'].extend(tos['tos_071'].pop('KIRK;'))
tos['tos_071']['SCOTT'].extend(tos['tos_071'].pop('SCOTT;'))
tos['tos_072']['KIRK'].extend(tos['tos_072'].pop('KIRK;'))
tos['tos_072']['SPOCK'].extend(tos['tos_072'].pop('SPOCK;'))
tos['tos_073']['SCOTT'].extend(tos['tos_073'].pop('SCOTT@'))
tos['tos_074']['MCCOY'].extend(tos['tos_074'].pop('MCCOY: Oh, those tricorder readings on Mister Flint are finally\r correlated'))
tos['tos_075']['KIRK'].extend(tos['tos_075'].pop("KIRK: But we don't steal space cruisers and act like irresponsible\r children. KIRK"))


tas = all_series['TAS']
tas['tas_001']['SPOCK'].extend(tas['tas_001'].pop('Y SPOCK'))
tas['tas_002']['SPOCK'].extend(tas['tas_002'].pop('SPOCK: Ready, Captain.'))
tas['tas_005']['KIRK'].extend(tas['tas_005'].pop('KIRK;'))
tas['tas_006']['SPOCK'].extend(tas['tas_006'].pop('G SPOCK'))
del tas['tas_009'][',']
tas['tas_010']['AREX'].extend(tas['tas_010'].pop('AREX [on viewscreen'))
tas['tas_020']['KIRK'].extend(tas['tas_020'].pop("KIRK: But we don't hate you. KUKULKAN"))
tas['tas_021']['UHURA'].extend(tas['tas_021'].pop('UHURA [on monitor}'))

tng = all_series['TNG']
tng['tng_001']['CRUSHER'].extend(tng['tng_001'].pop('CRUSHER:'))
tng['tng_001']['TROI'].extend(tng['tng_001'].pop('TROI: Bill.\r RIKER'))
tng['tng_002']['PICARD'].extend(tng['tng_002'].pop('PICARD: Absolutely not. This vaccine sample is a gift of life and we\r are honoured at receiving it. Would you do us the additional honour of\r now letting us entertain you?\r LUTAN'))
tng['tng_004']['WESLEY'].extend(tng['tng_004'].pop('WESLEY: Parts of him disappeared and then came back. Nobody else was\r paying attention to him the first time.\r RIKER'))
tng['tng_004']['WESLEY'].extend(tng['tng_004'].pop("WESLEY: No! He's very weak. TRAVELLER"))
tng['tng_010']['DATA'].extend(tng['tng_010'].pop('DATA: Computer'))
tng['tng_012']['BEATA'].extend(tng['tng_012'].pop('BEATA:'))
tng['tng_012']['CRUSHER'].extend(tng['tng_012'].pop('CRUSHER:'))
tng['tng_012']['DATA'].extend(tng['tng_012'].pop('DATA:'))
tng['tng_012']['LAFORGE'].extend(tng['tng_012'].pop('LAFORGE:'))
tng['tng_012']['PICARD'].extend(tng['tng_012'].pop('PICARD:'))
tng['tng_012']['PICARD'].extend(tng['tng_012'].pop('PICARD: Indeed we do. Mister Data, set course for the Neutral Zone.\r Warp six. DATA'))
tng['tng_012']['TASHA'].extend(tng['tng_012'].pop('TASHA:'))
tng['tng_014']['DATA'].extend(tng['tng_014'].pop('DATA: I am sorry, sir. That does not correspond with the information in\r my tricorder, sir.\r JAMESON'))
tng['tng_017']['PICARD'].extend(tng['tng_017'].pop('PICARD: And when I tell you, pull up hard.\r JAKE'))
tng['tng_019']['PICARD'].extend(tng['tng_019'].pop("PICARD: Ensign T'Su?\r T'SU"))
tng['tng_019']['WORF'].extend(tng['tng_019'].pop("WORF: No use. It's gone again. SOLIS"))
tng['tng_024']['DATA'].extend(tng['tng_024'].pop('DATA:'))
tng['tng_024']['PICARD'].extend(tng['tng_024'].pop('PICARD:'))
tng['tng_027']['PULASKI'].extend(tng['tng_027'].pop('PULASKI: You see? LAFORGE'))
tng['tng_028']['COMIC'].extend(tng['tng_028'].pop("COMIC: It's probably best when you do something like this. Need a cigar\r 'cos it's kind a prop kind of thing and you go like this and DATA"))
tng['tng_028']['DATA'].extend(tng['tng_028'].pop('DATA: Nothing makes me laugh. I wish to learn. COMIC'))
tng['tng_028']['PICARD'].extend(tng['tng_028'].pop("PICARD: No, they could fire until their lasers ran dry and they\r wouldn't hurt the Enterprise. My predicament is what to do with you.\r OKONA"))
tng['tng_033']['PULASKI'].extend(tng['tng_033'].pop("PULASKI: I couldn't disagree more. We'll save that argument for another\r day. DATA"))
tng['tng_035']['LAFORGE'].extend(tng['tng_035'].pop("LAFORGE: Okay. In the event of a breach of seal integrity there's an\r emergency release system which dumps the antimatter.\r DATA"))
tng['tng_045']['TROI'].extend(tng['tng_045'].pop('TROI + PULASKI'))
tng['tng_050']['PICARD'].extend(tng['tng_050'].pop("PICARD: Good. That's good. You see, my people once lived in caves. And\r then we learned to build huts and, in time, to build ships like this\r one.\r NURIA"))
tng['tng_054']['TROI'].extend(tng['tng_054'].pop('CRUSHER + TROI'))
tng['tng_056']['PICARD'].extend(tng['tng_056'].pop('PICARD;'))
tng['tng_059']['LAFORGE'].extend(tng['tng_059'].pop('LAFORGE + DATA'))
tng['tng_061']['PICARD'].extend(tng['tng_061'].pop('PICARD: Is there any possibility she could survive?\r DATA'))
tng['tng_065']['PICARD'].extend(tng['tng_065'].pop('PICARD + RIKER'))
tng['tng_065']['RIKER'].extend(tng['tng_065'].pop('PIKER'))
tng['tng_066']['TAM'].extend(tng['tng_066'].pop('TAM + TROI'))
tng['tng_071']['JOHN'].extend(tng['tng_071'].pop('JOHN: Unfortunately, Captain, my memories begin the moment I woke up in\r Sickbay. Doctor Crusher told me you think I was in some kind of battle.\r PICARD'))
tng['tng_080']['JEAN-LUC'].extend(tng['tng_080'].pop('JEAN LUC'))
tng['tng_080']['RIKER'].extend(tng['tng_080'].pop('RIKER: Well, if she was married to me, she had to be patient.\r TROI'))
tng['tng_085']['DATA'].extend(tng['tng_085'].pop('DATA: She is a cornerstone of Ventaxian theology. It seems that Ardra\r came to Ventax Two and promised one thousand years of peace and\r prosperity, for a price. Upon her return, she would enslave the entire\r population. In Ventaxian culture, it is considered bad luck to speak\r her name out loud. CLARK'))
tng['tng_088']['DATA'].extend(tng['tng_088'].pop('DATA: Aye, sir. PICARD'))
tng['tng_097']['JENNA'].extend(tng['tng_097'].pop('JENNA: The Book of Love, chapter four, paragraph seventeen'))
tng['tng_100']['WORF'].extend(tng['tng_100'].pop('WORF: Starboard thrusters destroyed. I may be able to land but I will\r not be able to take off.\r RIKER'))
tng['tng_102']['DATA'].extend(tng['tng_102'].pop('DATA:'))
tng['tng_102']['DATA'].extend(tng['tng_102'].pop('DATA:'))
tng['tng_118']['CAMPIO'].extend(tng['tng_118'].pop('CAMPIO: And my escort, who need not be addressed in this company'))
tng['tng_122']['PICARD'].extend(tng['tng_122'].pop('PICARD: Situations like these are never easy, Number One. RO'))
tng['tng_150']['LAFORGE'].extend(tng['tng_150'].pop("LAFORGE: We could, but there could be fifty Borg down there waiting for\r us and we'd never even know it.\r RIKER"))


ds9 = all_series['DS9']
ds9['ds9_000']['SISKO'].extend(ds9['ds9_000'].pop("SISKO: Sorry to be late. Our friend Gul Dukat had some\r problems on the other side of the wormhole. I see you've had a few of\r your own. KIRA"))
ds9['ds9_001']['ODO'].extend(ds9['ds9_001'].pop('ODO@'))
ds9['ds9_001']['SISKO'].extend(ds9['ds9_001'].pop('SISKO: Repeat. Reduce your power immediately or we will open fire.\r TAHNA'))
del ds9['ds9_002'][',']
del ds9['ds9_014'][")O'Brien"]
ds9['ds9_019'].update({'CREWWOMAN': ds9['ds9_019'].pop('CREWWOMAN:')})
ds9['ds9_021']['SISKO'].extend(ds9['ds9_021'].pop('SISKO [OC}'))
ds9['ds9_025']['PEL'].extend(ds9['ds9_025'].pop('PEL [OC'))
ds9['ds9_039']['DAX'].extend(ds9['ds9_039'].pop('DAX [OC'))
ds9['ds9_039']["O'BRIEN"].extend(ds9['ds9_039'].pop("O'BRIEN: Commander, I'm picking up two Federation ships headed our\r way.\r SISKO"))
del ds9['ds9_046'][")T'Rul"]
ds9['ds9_060']['QUARK'].extend(ds9['ds9_060'].pop('QUARK: Doctor? What are you doing in here?\r DAX'))
ds9['ds9_070']["O'BRIEN"].extend(ds9['ds9_070'].pop("O'BRIEN et al"))
ds9['ds9_078']['DAX'].extend(ds9['ds9_078'].pop('DAX.'))
ds9['ds9_080']['JAKE'].extend(ds9['ds9_080'].pop('JAKE [on monitor'))
ds9['ds9_080']['JARESH-INYO'].extend(ds9['ds9_080'].pop('JARESH-INY0'))
ds9['ds9_081']['JOSEPH'].extend(ds9['ds9_081'].pop("JOSEPH: Worried? I'm scared to death. But I'll be damned if I'm going\r to let them change the way I live my life.\r SISKO"))
del ds9['ds9_085'][',']
ds9['ds9_096']['WORF'].extend(ds9['ds9_096'].pop("WORF + O'BRIEN: Q'apla!\r MARTOK"))
ds9['ds9_103']['DAX'].extend(ds9['ds9_103'].pop('DAX: Miss me?\r ODO'))
ds9['ds9_116']['TAVANA'].extend(ds9['ds9_116'].pop('TAVANA + ALL'))
ds9['ds9_126']['ZIYAL'].extend(ds9['ds9_126'].pop('ZIYAL: What are you going to do when he wakes up?\r KIRA'))
del ds9['ds9_130']['!']
ds9['ds9_130']['DAMAR'].extend(ds9['ds9_130'].pop('DAMAR [on viewscreen'))
ds9['ds9_130']['LOEWS'].extend(ds9['ds9_130'].pop('LOWES'))
del ds9['ds9_136']["O'Brien's"]
ds9['ds9_136']['ODO'].extend(ds9['ds9_136'].pop('ODO + Odo'))
ds9['ds9_140']['ODO'].extend(ds9['ds9_140'].pop('ODO {OC]'))
ds9['ds9_142']['ODO'].extend(ds9['ds9_142'].pop("ODO: Somebody has to. Besides, everyone expects me to be dour and\r suspicious. I don't want to disappoint them.\r KIRA"))
ds9['ds9_142']['SISKO'].extend(ds9['ds9_142'].pop('SISKO: Eat fruit?\r DAX'))
ds9['ds9_142']['SISKO'].extend(ds9['ds9_142'].pop('SISKO: Have you made any more progress? Good news or bad?\r DAX'))
ds9['ds9_142']['SISKO'].extend(ds9['ds9_142'].pop("SISKO: You and I haven't always seen things eye to eye, but we have one\r thing in common. We both believe that the Prophets have a plan for\r Bajor. Sometimes it's not easy to see the path they've laid out for us.\r Right now, I don't know what they want from me, but I'm willing to take\r a leap of faith and trust that they're guiding me, and I'm asking you\r to take that leap with me.\r WINN"))
ds9['ds9_148']['SISKO'].extend(ds9['ds9_148'].pop('SISKO: Jake, if I never see another clam BOTH'))
ds9['ds9_154']['KOLANA'].extend(ds9['ds9_154'].pop('KOLANA [OC}'))
ds9['ds9_156']['KIRA'].extend(ds9['ds9_156'].pop('KIRA: I want to find Mika. FALA'))
ds9['ds9_157']['PALANCE'].extend(ds9['ds9_157'].pop("PALANCE: What's that mean to you, Shane. VIC"))
ds9['ds9_160']['KIRA'].extend(ds9['ds9_160'].pop('EZRI + KIRA'))
ds9['ds9_160']['JORAN'].extend(ds9['ds9_160'].pop("JORAN: No, we don't have time. We have work to do.\r EZRI"))
ds9['ds9_161']["O'BRIEN"].extend(ds9['ds9_161'].pop("0'BRIEN"))
ds9['ds9_172']['ROSS'].extend(ds9['ds9_172'].pop('ROSS:'))
ds9['ds9_172']['WEYOUN'].extend(ds9['ds9_172'].pop('WEYOUN:'))


voy = all_series['VOY']
voy['voy_004']['EMH'].extend(voy['voy_004'].pop('EMH: This is the Doctor speaking. Please activate your monitor to\r the Emergency Medical Holographic Channel. I believe I may have a\r suggestion that will help.'))
voy['voy_011']['KIM'].extend(voy['voy_011'].pop('KIM:'))
voy['voy_011']['TORRES'].extend(voy['voy_011'].pop('TORRES:'))
voy['voy_015']['CHAKOTAY'].extend(voy['voy_015'].pop('CHAKOTAY {OC]'))
voy['voy_022']['EMH'].extend(voy['voy_022'].pop('EMH [on monitor}'))
voy['voy_030'].update({'JONES': voy['voy_030'].pop('JONES: Jones. PARIS')})
voy['voy_049']['COLONEL Q'].extend(voy['voy_049'].pop('COLONEL\r Q'))
voy['voy_049']['FEMALE Q'].extend(voy['voy_049'].pop('FEMALE\r Q'))
voy['voy_055']['RILEY'].extend(voy['voy_055'].pop('RILEY: An hour, maybe two. Long enough.'))
voy['voy_056']['EVIL EMH'].extend(voy['voy_056'].pop('EVIL\r EMH'))
voy['voy_059']['CHAKOTAY'].extend(voy['voy_059'].pop('CHAKOTAY?'))
voy['voy_060']['JEFFREY'].extend(voy['voy_060'].pop('JEFFERY'))
voy['voy_061']['PARIS'].extend(voy['voy_061'].pop('PARIS [OC}'))
voy['voy_062']['JARLATH'].extend(voy['voy_062'].pop('JARLETH'))
voy['voy_063']['HOLO-CHAKOTAY'].extend(voy['voy_063'].pop('HOLO-CHAKOTAY\r on monitor]'))
voy['voy_064']['JANEWAY'].extend(voy['voy_064'].pop("JANEWAY: In the words of Jean-Luc Picard. 'In their Collective state,\r the Borg are utterly without mercy, driven by one will alone"))
voy['voy_067']['BRONE'].extend(voy['voy_067'].pop('l BRONE'))
voy['voy_068']['DEJAREN'].extend(voy['voy_068'].pop('DEJARAN'))
voy['voy_071']['ZAHL OFFICIAL'].extend(voy['voy_071'].pop('ZAHL\r OFFICIAL'))
voy['voy_072']['CREWMAN'].extend(voy['voy_072'].pop('CREWMAN:'))
voy['voy_072']['NIMIRA'].extend(voy['voy_072'].pop('NIMIRA: Under one condition'))
voy['voy_075']['DREAM ALIEN'].extend(voy['voy_075'].pop('DREAM\r ALIEN'))
voy['voy_080']['PARIS'].extend(voy['voy_080'].pop('PARIS: August 29, 1936, 12'))
voy['voy_080']['YOUNG HIROGEN'].extend(voy['voy_080'].pop('YOUNG\r HIROGEN'))
voy['voy_081']['PARIS/STETH'].extend(voy['voy_081'].pop('PARIS?STETH'))
voy['voy_081']['PARIS/STETH'].extend(voy['voy_081'].pop('STETH as PARIS'))
voy['voy_082']['JANEWAY'].extend(voy['voy_082'].pop('JAEWAY'))
voy['voy_083']['KELLIN'].extend(voy['voy_083'].pop('KELLIN [OC}'))
voy['voy_091']['CHAKOTAY'].extend(voy['voy_091'].pop('CHAKOTAY: A long one. A Cave Beyond Logic'))
voy['voy_091']['CHAKOTAY'].extend(voy['voy_091'].pop('CHAOTAY'))
voy['voy_092']['FLOTTER'].extend(voy['voy_092'].pop('FLOTTER [OC}'))
voy['voy_093']['EMH'].extend(voy['voy_093'].pop('EMH: I\r have it. Her cybernetic systems were terminated on Stardate 52164.3.\r Borg time index'))
voy['voy_096']['ADMIRAL PARIS'].extend(voy['voy_096'].pop('ADMIRAL\r PARIS'))
voy['voy_098']['JANEWAY'].extend(voy['voy_098'].pop('JANEWAY;'))
voy['voy_099'].update({'NARRATOR': voy['voy_099'].pop('NARRATOR:\r The Adventures of Captain Proton! Chapter Eighteen')})
voy['voy_100']['VULCAN MASTER'].extend(voy['voy_100'].pop('VULCAN\r MASTER'))
voy['voy_100']['YOUNG TUVOK'].extend(voy['voy_100'].pop('YOUNG\r TUVOK'))
voy['voy_101']['QATAI'].extend(voy['voy_101'].pop('QATAI [OC'))
voy['voy_101']['QATAI'].extend(voy['voy_101'].pop('QATATI'))
voy['voy_102']['MAGNUS'].extend(voy['voy_102'].pop('MAGNUS\r: Field notes, U.S.S. Raven, Stardate 32623.5'))
voy['voy_102']['MAGNUS'].extend(voy['voy_102'].pop('MAGNUS\r: Field notes, U.S.S. Raven, Stardate 32629.4'))
voy['voy_106']['ARTIFICIAL INTELLIGENCE'].extend(voy['voy_106'].pop('ARTIFICIAL\r INTELLIGENCE'))
voy['voy_112']['EMH'].extend(voy['voy_112'].pop('EMH [OC}'))
voy['voy_113']['ALL'].extend(voy['voy_113'].pop('ALL: Agreed'))
voy['voy_113']['FOUR OF NINE'].extend(voy['voy_113'].pop('FOUR OF\r NINE'))
voy['voy_113']['FOUR OF NINE'].extend(voy['voy_113'].pop('FOUR'))
voy['voy_113']['THREE OF NINE'].extend(voy['voy_113'].pop('THREE'))
voy['voy_113']['THREE OF NINE'].extend(voy['voy_113'].pop('THREE OF\r NINE'))
voy['voy_113']['TWO OF NINE'].extend(voy['voy_113'].pop('TWO'))
voy['voy_113']['TWO OF NINE'].extend(voy['voy_113'].pop('TWO\xa0[OC]'))
voy['voy_113']['TWO OF NINE'].extend(voy['voy_113'].pop('TWO [OC}'))
voy['voy_116']['ALICE'].extend(voy['voy_116'].pop('ALICE\r [OC}'))
voy['voy_121']['ADMIRAL PARIS'].extend(voy['voy_121'].pop('ADMIRAL\r PARIS'))
voy['voy_121']['HARKINS'].extend(voy['voy_121'].pop('HAWKINS'))
voy['voy_123']['GOTANA-RETZ'].extend(voy['voy_123'].pop('GOTATA-RETZ'))
voy['voy_125']['SOLDIER'].extend(voy['voy_125'].pop('SOLDIER ONE'))
voy['voy_125']['SOLDIER'].extend(voy['voy_125'].pop('SOLDER'))
voy['voy_127']['SEVEN'].extend(voy['voy_127'].pop('SEVEN;'))
voy['voy_130']['JANEWAY'].extend(voy['voy_130'].pop('JANEWAY;'))
voy['voy_130']['YIFAY'].extend(voy['voy_130'].pop('YIVEL'))
voy['voy_132']['ZAR'].extend(voy['voy_132'].pop('ZAR:'))
voy['voy_134']['AYALA'].extend(voy['voy_134'].pop('AYALA:'))
voy['voy_134']['VIDIIAN'].extend(voy['voy_134'].pop('VIIDIAN'))
voy['voy_134']['YOUNG KES'].extend(voy['voy_134'].pop('YOUNG\r KES'))
voy['voy_137']['ALIEN BOY'].extend(voy['voy_137'].pop('ALIEN\r BOY'))
voy['voy_137']['ALIEN BOY'].extend(voy['voy_137'].pop('ALIEN CHILD'))
voy['voy_139']['KIM'].extend(voy['voy_139'].pop('KIM|'))
voy['voy_142']['ADMIRAL PARIS'].extend(voy['voy_142'].pop('ADMIRAL\r PARIS'))
voy['voy_145']['ALPHA 2'].extend(voy['voy_145'].pop('ALPHA\r 2'))
voy['voy_146']['ADULT NAOMI'].extend(voy['voy_146'].pop('ADULT\r NAOMI'))
voy['voy_149']["T'GRETH"].extend(voy['voy_149'].pop("T'GRETH?"))
voy['voy_149']['TUVOK'].extend(voy['voy_149'].pop('TUVOK: Computer, security override. Authorisation'))
voy['voy_150']['GARON'].extend(voy['voy_150'].pop('GARON [on screen'))
voy['voy_151']['KIM'].extend(voy['voy_151'].pop('KIM:'))
voy['voy_151']['MED TECH'].extend(voy['voy_151'].pop('MED\r TECH'))
voy['voy_154']['IRENE HANSON'].extend(voy['voy_154'].pop('IRENE\r HANSON'))
voy['voy_154']['JOHN TORRES'].extend(voy['voy_154'].pop('JOHN\r TORRES'))
voy['voy_154']['MARY KIM'].extend(voy['voy_154'].pop('MARY\r KIM'))
voy['voy_156']['PARIS'].extend(voy['voy_156'].pop('PARIS:'))
voy['voy_156']['PORT AUTHORITY OFFICER'].extend(voy['voy_156'].pop('PORT\r AUTHORITY OFFICER'))
voy['voy_159']['ADMIRAL PARIS'].extend(voy['voy_159'].pop('ADMIRAL\r PARIS'))
voy['voy_159']['ADMIRAL PARIS'].extend(voy['voy_159'].pop('ADMIRAL'))
voy['voy_159']['BORG'].extend(voy['voy_159'].pop('BORG\r: Vessel identified'))


ent = all_series['ENT']
ent['ent_000']['TRAVIS'].extend(ent['ent_000'].pop('TRAVIS [OC}'))
del ent['ent_002']["T'Pol"]
ent['ent_003']['DILLARD'].extend(ent['ent_003'].pop('DILLARD?'))
ent['ent_003']["TRENA'L"].extend(ent['ent_003'].pop("TRENA'L:"))
ent['ent_004']['VOICE'].extend(ent['ent_004'].pop('VOICE [OC}'))
ent['ent_007']["T'POL"].extend(ent['ent_007'].pop("T'POL [OC}"))
ent['ent_014']['HOSHI'].extend(ent['ent_014'].pop('HOSHI [OC}'))
ent['ent_015']["T'POL"].extend(ent['ent_015'].pop("T'POL;"))
ent['ent_019']['GRAT'].extend(ent['ent_019'].pop('GRAT [on viewscreen'))
ent['ent_020']['CAPTAIN'].extend(ent['ent_020'].pop('CAPTAIN [on viewscreen'))
ent['ent_025']['RAAN'].extend(ent['ent_025'].pop('RAAN[OC]'))
ent['ent_026']['MESTRAL'].extend(ent['ent_026'].pop('MESTRA'))
ent['ent_027']['REED'].extend(ent['ent_027'].pop('REED [OC}'))
del ent['ent_031']["T'Pol's"]
ent['ent_034']['ARCHER'].extend(ent['ent_034'].pop('ARCHER [OC}'))
ent['ent_034']['HOSHI'].extend(ent['ent_034'].pop('HOSIHI'))
ent['ent_034']['TRAVIS'].extend(ent['ent_034'].pop('TRAVIS:'))
del ent['ent_039'][')']
ent['ent_041']['TUCKER'].extend(ent['ent_041'].pop('TUCKER [OC}'))
ent['ent_042']["T'POL"].extend(ent['ent_042'].pop("T'POL: T'POL"))
ent['ent_044']['DOCTOR F'].extend(ent['ent_044'].pop('DOCTOR F:'))
ent['ent_048']['ARCHER'].extend(ent['ent_048'].pop('ARCHER\r [OC}'))
ent['ent_049']['SKALAAR'].extend(ent['ent_049'].pop('SKALARR'))
ent['ent_054']['TUCKER'].extend(ent['ent_054'].pop('TUCKER [OC}'))
ent['ent_055']['HOSHI'].extend(ent['ent_055'].pop('HOSHI:'))
del ent['ent_055']["T'Pol"]
ent['ent_059']['ARCHER'].extend(ent['ent_059'].pop('ARCHER [OC}'))
ent['ent_060']['ARCHER'].extend(ent['ent_060'].pop('ARCHER\r {OC}'))
ent['ent_060']['ARCHER'].extend(ent['ent_060'].pop('ARCHER:'))
ent['ent_060']['PHLOX'].extend(ent['ent_060'].pop('PHLOX [OC}'))
ent['ent_061']['ARCHER'].extend(ent['ent_061'].pop('ARC HER'))
del ent['ent_061']["T'Pol"]
ent['ent_063']['TALAS'].extend(ent['ent_063'].pop('TALAS [OC}'))
ent['ent_068']['VOICE'].extend(ent['ent_068'].pop('VOICE [OC}'))
ent['ent_073']['AQUATIC 2'].extend(ent['ent_073'].pop('AQUATIC2'))
del ent['ent_075']['OC]']
ent['ent_076']['VOSK'].extend(ent['ent_076'].pop("VOSK: You are a fool. You think we're equals because I allow you to\r participate in this struggle. You fight to control nations. We dominate\r entire worlds. We extend our will across time. If your race were to\r endure for a million years, you couldn't begin to approach what we've\r accomplished. The next time you feel the urge to threaten me, remember\r this"))
ent['ent_078']['VOICE'].extend(ent['ent_078'].pop('VOICE [OC}'))
ent['ent_080']['ARCHER'].extend(ent['ent_080'].pop('ARCHER [OC}'))
ent['ent_080']['SOONG'].extend(ent['ent_080'].pop("SOONG: If the Klingons retaliate against Earth, it'll make the Xindi\r Incident look like a lovers' quarrel.\r ARCHER"))
ent['ent_082']['ARCHER'].extend(ent['ent_082'].pop('ARCHER;'))
ent['ent_082']['HOSHI'].extend(ent['ent_082'].pop('HOSHI;'))
ent['ent_082']['SOVAL'].extend(ent['ent_082'].pop('SOVAL;'))
ent['ent_082']['TUCKER'].extend(ent['ent_082'].pop('TUCKER:'))
ent['ent_083']['SOVAL'].extend(ent['ent_083'].pop('SOVAL;'))
ent['ent_086']['VALDORE'].extend(ent['ent_086'].pop('VALDORE:'))
ent['ent_088']['ARCHER'].extend(ent['ent_088'].pop('ARCHER;'))
ent['ent_088']['LISSAN'].extend(ent['ent_088'].pop('LISSAN;'))
ent['ent_088']['PHLOX'].extend(ent['ent_088'].pop('PHLOX;'))
ent['ent_088']['REED'].extend(ent['ent_088'].pop('REED;'))
ent['ent_088']['SHRAN'].extend(ent['ent_088'].pop('SHRAN;'))
ent['ent_090']["K'VAGH"].extend(ent['ent_090'].pop("K'VAGHNow,"))
ent['ent_093']['PHLOX'].extend(ent['ent_093'].pop('PHLOX;'))
ent['ent_093']['SOVAL'].extend(ent['ent_093'].pop('SOVAL;'))
ent['ent_094']['REED'].extend(ent['ent_094'].pop('REED: The autopsy data confirms what we already\r knew'))
ent['ent_096']['SHRAN'].extend(ent['ent_096'].pop('SHRAN:'))


dis = all_series['DIS']
dis['dis_000']['WEETON'].extend(dis['dis_000'].pop('WEEDON'))
dis['dis_001']['SARU'].extend(dis['dis_001'].pop('SANU'))
dis['dis_001']['BURNHAM'].extend(dis['dis_001'].pop('BUNRHAM'))
dis['dis_003']['CULBER'].extend(dis['dis_003'].pop('CULPER'))
dis['dis_003']['OWOSEKUN'].extend(dis['dis_003'].pop('OWOSEKUM'))
dis['dis_003']['RANCE'].extend(dis['dis_003'].pop('RANCE[OC]'))
dis['dis_004']['CORNWELL'].extend(dis['dis_004'].pop('CORNWALL'))
dis['dis_004']['SARU'].extend(dis['dis_004'].pop('DARU'))
dis['dis_004']['STAMETS'].extend(dis['dis_004'].pop('STAMET'))
dis['dis_005']['AMANDA'].extend(dis['dis_005'].pop('AMANDAL'))
dis['dis_005']['BURNHAM'].extend(dis['dis_005'].pop('MICHAEL'))
dis['dis_006']['BURNHAM'].extend(dis['dis_006'].pop('STAMETS + BURNHAM'))
dis['dis_006']['BURNHAM'].extend(dis['dis_006'].pop('\ufeffBURNHAM'))
dis['dis_007']['OWOSEKUN'].extend(dis['dis_007'].pop('OWOSEKUM'))
dis['dis_008']['SARU'].extend(dis['dis_008'].pop('SARY'))
dis['dis_008']['TERREL'].extend(dis['dis_008'].pop('TERREL [hologram}'))
dis['dis_008']['TERREL'].extend(dis['dis_008'].pop("TERREL Admiral Cornwell's emergency medical shuttle has successfully arrived at Starbase 88. \r She is currently undergoing surgery. I'm told she should make a total recovery.\r LORCA"))
dis['dis_009']['BRYCE'].extend(dis['dis_009'].pop('BRUCE'))
dis['dis_010']['TYLER'].extend(dis['dis_010'].pop('TYLE'))
dis['dis_012']['AIRIAM'].extend(dis['dis_012'].pop('ARIAM'))
dis['dis_012']['BURNHAM'].extend(dis['dis_012'].pop('BURNAM'))
dis['dis_013']['BRYCE'].extend(dis['dis_013'].pop('BRUCE'))
dis['dis_013']['STAMETS'].extend(dis['dis_013'].pop('STAMET'))
dis['dis_013']['STAMETS'].extend(dis['dis_013'].pop('STAMETS:'))
dis['dis_014']['BRYCE'].extend(dis['dis_014'].pop('BRUCE'))
dis['dis_015']['AIRIAM'].extend(dis['dis_015'].pop('ARIAM'))
dis['dis_015']['BURNHAM'].extend(dis['dis_015'].pop('BURHAM'))
dis['dis_015']['CONNOLLY'].extend(dis['dis_015'].pop('CONNELLY'))
dis['dis_015']['OWOSEKUN'].extend(dis['dis_015'].pop('DETMER + OWOSEKUN'))
dis['dis_016']['OWOSEKUN'].extend(dis['dis_016'].pop('BURNHAM + OWOSEKUN'))
dis['dis_016']['OWOSEKUN'].extend(dis['dis_016'].pop('OWOSEKIN'))
dis['dis_016']['PIKE'].extend(dis['dis_016'].pop('PILE'))
dis['dis_017']['BURNHAM'].extend(dis['dis_017'].pop('BURNAM'))
dis['dis_019']['BURNHAM'].extend(dis['dis_019'].pop('BURNAM'))
dis['dis_019']['LELAND'].extend(dis['dis_019'].pop('LELAND [on viewscreen'))
dis['dis_019']['OWOSEKUN'].extend(dis['dis_019'].pop('OWOSEKIN'))
dis['dis_020']['BURNHAM'].extend(dis['dis_020'].pop('BURNHA'))
dis['dis_020']['OWOSEKUN'].extend(dis['dis_020'].pop('OWOSEKIN'))
dis['dis_021']['PIKE'].extend(dis['dis_021'].pop('PIE'))
dis['dis_023']['OWOSEKUN'].extend(dis['dis_023'].pop('OWOSEKUM'))
dis['dis_024']['CORNWELL'].extend(dis['dis_024'].pop('CORNWLL'))
dis['dis_025']['GABRIELLE'].extend(dis['dis_025'].pop('GALRIELLE'))
dis['dis_025']['GEORGIOU'].extend(dis['dis_025'].pop('GEORGIOY'))
dis['dis_028']['NICOLA'].extend(dis['dis_028'].pop('NICHOLA'))
dis['dis_028']['RHYS'].extend(dis['dis_028'].pop('RHSYS'))
dis['dis_028']['SPOCK'].extend(dis['dis_028'].pop('SPOCK: Personal log. Stardate'))
dis['dis_030']['OWOSEKUN'].extend(dis['dis_030'].pop('DETMER + OWOSEKUN'))
dis['dis_030']['NHAN'].extend(dis['dis_030'].pop('NHAH'))
dis['dis_031']['BOOK'].extend(dis['dis_031'].pop('BOOKS'))
dis['dis_031']['BRYCE'].extend(dis['dis_031'].pop('BRYE'))
dis['dis_031']['BURNHAM'].extend(dis['dis_031'].pop('BURNHAM You could come with us, to Earth.\r BOOK'))
dis['dis_031']['OWOSEKUN'].extend(dis['dis_031'].pop('OWODEKUN'))
dis['dis_031']['OWOSEKUN'].extend(dis['dis_031'].pop('OWOSEKUNN'))
dis['dis_031']['TILLY'].extend(dis['dis_031'].pop('TIILY'))
dis['dis_035']['BURNHAM'].extend(dis['dis_035'].pop('BURHAM'))
dis['dis_035']['SARU'].extend(dis['dis_035'].pop('SARu'))
dis['dis_036']['BRYCE'].extend(dis['dis_036'].pop('BRUCE'))
dis['dis_036']['BURNHAM'].extend(dis['dis_036'].pop('BURNAM'))
dis['dis_036']['BURNHAM'].extend(dis['dis_036'].pop('BURNHMAM'))
dis['dis_037']['KELPIEN'].extend(dis['dis_037'].pop('KELPIAN'))
dis['dis_038']['BURNHAM'].extend(dis['dis_038'].pop('BURHAM'))
dis['dis_038']['OWOSEKUN'].extend(dis['dis_038'].pop('OWOSEKIN'))
dis['dis_038']['SARU'].extend(dis['dis_038'].pop('SAR'))
dis['dis_039']['COMPUTER'].extend(dis['dis_039'].pop('CUMPUTER'))
dis['dis_040']['KANAK'].extend(dis['dis_040'].pop('KANEK'))
del dis['dis_041']['-']
dis['dis_041']['BURNHAM'].extend(dis['dis_041'].pop('BURNHAN'))
dis['dis_041']['OSYRAA'].extend(dis['dis_041'].pop('OSYRAAL'))
dis['dis_041']['SAHIL'].extend(dis['dis_041'].pop('SAHHIL'))


pic = all_series['PIC']
pic['pic_000']['BING CROSBY'].extend(pic['pic_000'].pop('CROSBY'))
pic['pic_004']['BJAYZL'].extend(pic['pic_004'].pop('BJAYJL'))
pic['pic_004']['BJAYZL'].extend(pic['pic_004'].pop('BJAYZI'))


json_TOS = json.dumps(tos)
with open("TOS.json", "w") as f:
    f.write(json_TOS)
json_TAS = json.dumps(tas)
with open("TAS.json", "w") as f:
    f.write(json_TAS)
json_TNG = json.dumps(tng)
with open("TNG.json", "w") as f:
    f.write(json_TNG)
json_DS9 = json.dumps(ds9)
with open("DS9.json", "w") as f:
    f.write(json_DS9)
json_VOY = json.dumps(voy)
with open("VOY.json", "w") as f:
    f.write(json_VOY)
json_ENT = json.dumps(ent)
with open("ENT.json", "w") as f:
    f.write(json_ENT)
json_DIS = json.dumps(dis)
with open("DIS.json", "w") as f:
    f.write(json_DIS)
json_PIC = json.dumps(pic)
with open("PIC.json", "w") as f:
    f.write(json_PIC)


ALL = {'TOS': tos, 'TAS': tas, 'TNG': tng, 'DS9': ds9, 'VOY': voy,
       'ENT': ent, 'DIS': dis, 'PIC': pic}
json_ALL = json.dumps(ALL)
with open("StarTrekDialogue.json", "w") as f:
    f.write(json_ALL)

pass
